### ISSUE TITLE
Push Notification Certificate

### ISSUE THREAD

**Issue by studiozocaro** [isilher/red-vs-blue#12]
Hi,
 are you solution for Push Notification Certificate ?

**Comment by isilher** [comment]
Hey there, I'm not sure I understand the question. If you want to assign an iOS certificate for push notifications to your app, you can generate one in the apple developer interface. When working with a white-label app with two versions, you would then do one of two things:

1. Use one certificate for both apps by assigning the same certificate to two bundle identifiers.
2. Generate two different certificates and assign each to a different bundle identifier.

The certificates will then be applied to the app when generating deployable builds. How you do this is outside the scope of this example, but I would personally advise to look into [Fastlane](https://fastlane.tools).

Hope this helps!

**Comment by mwmcode** [comment]
Hi @isilher, didn't want to open a new issue/question so thought I ask here: I see that you're passing appName for android commands in `package.json`
```json
    "android:blue": "yarn env:blue && react-native run-android --appId com.redvsblue.blue",
```
what about iOS? where will bundleIds for iOS go in this case? 

> context: I have 2 apps that will use the same components and libs but need to be published under different names and am thinking that your approach fits this scenario. Each of the 2 apps will need its own bundleId, hence the question above.
> I'm thinking that `App.js` or `index.js` can import 2 sets of screens (app1 and app2) and renders/builds based on some env var

**Comment by isilher** [comment]
Hi @mchasaegh, feel free to open new issues for questions :-) I'll answer this one here:

> I see that you're passing appName for android commands in package.json

The reason the `appId` is supplied in the `run-android` command is that otherwise the command does not know which app to open after building it. (see also: https://github.com/isilher/red-vs-blue#gotchas). You can choose to omit the flag: the app will successfully build but not open. You can then manually open it from the app drawer. In my experience this can lead to confusion when you have multiple versions of the same app on the test device, which is likely to happen in the white-label scenario.

> what about iOS? where will bundleIds for iOS go in this case?

There is no need to specify the bundleId when running the `react-native run-is` command. The correct app will automatically be opened on the simulator.
